name: Azure pipeline

on:
  push:
    branches:
    - main

env:
  TERRAFORM_VERSION  : 1.9.7
  ARM_CLIENT_ID      : ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET  : ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID      : ${{ secrets.ARM_TENANT_ID }}
#a
jobs:

  tf-run:
    name: Terraform on Azure
    runs-on: ubuntu-latest
 
    steps:

    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.7

    - name: Step 02 - Terraform Version
      run : terraform --version

    - name: Step 03 - CheckOut GitHub Repo
      uses: actions/checkout@v4

    - name: Step 04 - Terraform Init
      run : terraform -chdir=./terraform/ init

    - name: Step 05 - Terraform Validate
      run : terraform -chdir=./terraform validate

    - name: Step 06 - Terraform Plan
      run : terraform -chdir=./terraform/ plan -out tfplan
      # run : terraform -chdir=./terraform plan -input=false -destroy -out tfplan

    - name: Step 07 - Terraform Apply
      run : terraform -chdir=./terraform/ apply tfplan

    - name: Step 08 - Terraform Show
      run : terraform -chdir=./terraform show